// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZeLYAUTQVfchRpnM78e1mnEKjwd_R9WU',
    appId: '1:184019483421:web:e29420bbe4c776799a3ff4',
    messagingSenderId: '184019483421',
    projectId: 'flash-f507c',
    authDomain: 'flash-f507c.firebaseapp.com',
    storageBucket: 'flash-f507c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcDLmi2ljVU2uh2KtOVCf7zs6iLLynYHc',
    appId: '1:184019483421:android:d858f8f5ded7b1169a3ff4',
    messagingSenderId: '184019483421',
    projectId: 'flash-f507c',
    storageBucket: 'flash-f507c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADDkFUgf2iFVG-S1ZpqdZ-MkaB6D0QhPw',
    appId: '1:184019483421:ios:134c2a00dd7939799a3ff4',
    messagingSenderId: '184019483421',
    projectId: 'flash-f507c',
    storageBucket: 'flash-f507c.appspot.com',
    iosClientId: '184019483421-bnd6f9tslcuuck2s7rqm15bnm725nrua.apps.googleusercontent.com',
    iosBundleId: 'flash.flash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADDkFUgf2iFVG-S1ZpqdZ-MkaB6D0QhPw',
    appId: '1:184019483421:ios:5d399270b878318b9a3ff4',
    messagingSenderId: '184019483421',
    projectId: 'flash-f507c',
    storageBucket: 'flash-f507c.appspot.com',
    iosClientId: '184019483421-b0mrqd6j3odqf6bmj07c9hdi8lg4624s.apps.googleusercontent.com',
    iosBundleId: 'flash.flash.RunnerTests',
  );
}
